took json and convert to csv and download in frontend, following suggested tutorial
Comes with error: collection.reduce is not a function, once this is ironed out everything should work